export const ERC20_ABI = [
  'function name() view returns (string)',
  'function symbol() view returns (string)',
  'function decimals() view returns (uint8)',
  'function balanceOf(address) view returns (uint256)',
  'function allowance(address owner,address spender) view returns (uint256)',
  'function approve(address spender,uint256 amount) returns (bool)',
  'function totalSupply() view returns (uint256)',
]

export const PMFI_FACTORY_V22_ABI = [
  'function USDC() view returns (address)',
  'function feeRecipient() view returns (address)',
  'function marketplace() view returns (address)',
  'function creationPaused() view returns (bool)',
  'function purchasesPaused() view returns (bool)',
  'function allVaults(uint256) view returns (address)',
  'function allVaultsLength() view returns (uint256)',
  'function isVault(address vault) view returns (bool)',
  'function creatorOf(address vault) view returns (address)',
  'function collateralAllowed(address collateral) view returns (bool)',
  'function CREATION_FEE() view returns (uint256)',
  'function MIN_FUNDING_PERIOD() view returns (uint256)',
  'function MAX_FUNDING_PERIOD() view returns (uint256)',
  'function MAX_REPAYMENT_PERIOD() view returns (uint256)',
  'function createPosition((address collateral,uint256 collateralAmount,uint256 targetRaiseUsdc,uint256 totalRepaymentUsdc,uint256 fundingDeadline,uint256 repaymentDeadline,string namePrefix,string symbolPrefix) params) payable returns (address vault,uint256 saleId)',
  'event PositionCreated(address indexed borrower,address indexed vault,address indexed collateral,address pToken,address nToken,uint256 collateralAmount,uint256 targetRaiseUsdc,uint256 totalRepaymentUsdc,uint256 fundingDeadline,uint256 repaymentDeadline,uint256 saleId)',
  'event CollateralAllowed(address indexed collateral,bool allowed)',
]

export const PMFI_MARKETPLACE_V22_ABI = [
  'function factory() view returns (address)',
  'function USDC() view returns (address)',
  'function feeRecipient() view returns (address)',
  'function SALE_FEE_BPS() view returns (uint256)',
  'function sales(uint256) view returns (address vault,address seller,address pToken,uint256 amountInitial,uint256 amountRemaining,uint256 usdcTotal,uint256 usdcRemaining,uint256 usdcRaisedToSeller,uint256 feeAccrued,uint256 expiry,bool active)',
  'function salesLength() view returns (uint256)',
  'function saleIdPlusOneByVault(address vault) view returns (uint256)',
  'function quoteUsdc(uint256 saleId,uint256 pAmount) view returns (uint256)',
  'function quoteFee(uint256 saleId,uint256 sellerPrice) view returns (uint256)',
  'function quoteTotalPayment(uint256 saleId,uint256 pAmount) view returns (uint256 sellerPrice,uint256 feeAmount,uint256 totalPaid)',
  'function buy(uint256 saleId,uint256 pAmount,uint256 maxTotalPayment)',
  'function cancel(uint256 saleId)',
  'function closeExpired(uint256 saleId)',
  'event SaleRegistered(uint256 indexed saleId,address indexed vault,address indexed seller,address pToken,address usdc,uint256 pAmount,uint256 totalUsdcPrice,uint256 expiry)',
  'event Bought(uint256 indexed saleId,address indexed buyer,uint256 pAmount,uint256 sellerPrice,uint256 feeAmount,uint256 totalPaid)',
  'event SaleClosed(uint256 indexed saleId,uint256 pBurnedAsUnfunded,bool fullyFilled,bool expired)',
]

export const PMFI_VAULT_V22_ABI = [
  'function factory() view returns (address)',
  'function marketplace() view returns (address)',
  'function borrower() view returns (address)',
  'function collateral() view returns (address)',
  'function usdc() view returns (address)',
  'function P() view returns (address)',
  'function N() view returns (address)',
  'function collateralDecimals() view returns (uint8)',
  'function usdcDecimals() view returns (uint8)',
  'function initialCollateralAmount() view returns (uint256)',
  'function targetRaiseUsdc() view returns (uint256)',
  'function totalRepaymentUsdc() view returns (uint256)',
  'function fundingDeadline() view returns (uint256)',
  'function repaymentDeadline() view returns (uint256)',
  'function initialized() view returns (bool)',
  'function fundingClosed() view returns (bool)',
  'function settled() view returns (bool)',
  'function closedWithoutOutstandingP() view returns (bool)',
  'function pairedN() view returns (uint256)',
  'function exercisedN() view returns (uint256)',
  'function usdcPaid() view returns (uint256)',
  'function accountedCollateral() view returns (uint256)',
  'function collateralRefundClaim() view returns (uint256)',
  'function repaymentRequiredUsdc() view returns (uint256)',
  'function repaymentRemainingUsdc() view returns (uint256)',
  'function canSettleEarly() view returns (bool)',
  'function previewRedeemP(uint256 amount) view returns (uint256 collateralOut,uint256 usdcOut)',
  'function legAddresses() view returns (address pToken,address nToken)',
  'function claimCollateralRefund(address recipient)',
  'function redeemPair(uint256 amount)',
  'function repayInFull()',
  'function settle()',
  'function settleAndRedeemP(uint256 amount)',
  'function redeemP(uint256 amount)',
  'event PositionInitialized(address indexed borrower,uint256 collateralAmount,uint256 pMintedToMarketplace,uint256 nMintedToBorrower)',
  'event FundingClosed(uint256 unsoldP,uint256 collateralRefundClaimRecorded,uint256 timestamp)',
  'event CollateralRefundClaimed(address indexed borrower,address indexed recipient,uint256 amount)',
  'event FullRepayment(address indexed borrower,uint256 nBurned,uint256 usdcPaid,uint256 collateralOut)',
  'event Settled(bool early,uint256 collateralPool,uint256 usdcPool,uint256 pSupply)',
  'event RedeemP(address indexed user,uint256 pAmount,uint256 collateralOut,uint256 usdcOut)',
  'event RedeemPair(address indexed user,uint256 amount,uint256 collateralOut)',
]
